{{- if and .Values.kafka.install (not .Values.global.externalKafka.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka.name" . }}-secret
  labels:
    automation.infra/secret-change: "true"
    {{- include "kafka.defaultLabels" . | nindent 4 }}
  annotations:
    kafkaservice.qubership.org/auto-restart: {{  .Values.kafka.autoRestartOnSecretChange | quote }}
type: Opaque
stringData:
  admin-username: "{{ include "kafka.adminUsername" . }}"
  admin-password: "{{ include "kafka.adminPassword" . }}"
  client-username: "{{ include "kafka.clientUsername" . }}"
  client-password: "{{ include "kafka.clientPassword" . }}"
  idp-whitelist: "{{ .Values.kafka.idpWhitelist }}"
  zookeeper-client-username: "{{ include "kafka.zooKeeperClientUsername" . }}"
  zookeeper-client-password: "{{ include "kafka.zooKeeperClientPassword" . }}"
{{- end }}