{{- $secretName := include "backupDaemon.s3.tlsSecretName" . }}
{{- if and $secretName .Values.backupDaemon.s3.enabled .Values.backupDaemon.s3.sslCert .Values.backupDaemon.s3.sslVerify (not (lookup "v1" "Secret" .Release.Namespace $secretName)) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  ca.crt: {{ .Values.backupDaemon.s3.sslCert | quote }}
{{- end }}