---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    crd.qubership.org/version: 1.9.0
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: akhqconfigs.qubership.org
spec:
  group: qubership.org
  names:
    kind: AkhqConfig
    listKind: AkhqConfigList
    plural: akhqconfigs
    singular: akhqconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              configs:
                items:
                  properties:
                    descriptor-file-base64:
                      type: string
                    key-type:
                      type: string
                    message-type:
                      type: string
                    topic-regex:
                      type: string
                  required:
                  - descriptor-file-base64
                  - message-type
                  - topic-regex
                  type: object
                type: array
            required:
            - configs
            type: object
          status:
            properties:
              isInvalid:
                type: boolean
              isProcessed:
                type: boolean
              problemConfigs:
                type: string
            required:
            - isInvalid
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
